name: Release

on:
  workflow_run:
    workflows: 
      - Versioning
    types:
      - completed

permissions:
  contents: write

jobs:
  build-and-publish-package:
    name: Build and publish package
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build package
        run: pnpm build
      
      - name: Publish package
        uses: simenandre/publish-with-pnpm@v2
        with:
          npm-auth-token: ${{ secrets.NPM_TOKEN }}
